import Head from 'next/head'
import Image from 'next/image'
// import { useState } from 'react'
import About from '../components/About'
import Contact from '../components/Contact'
import Hero from '../components/Hero'
// import Public from '../public/download.png'
// import styles from '../styles/Home.module.css'
import Narbar from "../components/Narbar"
import Sidebar from '../components/Sidebar'
import Skill from '../components/Skill'
import What from '../components/What'
import Work from '../components/Work'
// import React, { useEffect } from 'react'
import React, { useEffect, useState } from 'react'
import {useRouter}  from 'next/router'
import { collection, deleteDoc, doc, getDocs } from 'firebase/firestore';
import { database } from '../firebase';

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    if(!sessionStorage.getItem("username")){
      router.push('/auth/login')
      // setUsername(sessionStorage.getItem("username"))
    }
    
  }, [])
  
  return (
    <div >
      <Head>
        <title>Sharjeel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Narbar />
        
      </header>
      <main>
        {/* <Sidebar isOpen={isOpen} toggleSidebar={toggleSidebar}/> */}

        <Hero/>
        <About/>
        <What/>
        <Skill/>
        <Work/>
        <Contact/> 
      </main>
      
    </div>
  )
}
